### ISSUE TITLE
Define database schema

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/csc648group06#29]

**Comment by omegabytes** [comment]
this should ping slack

**Comment by omegabytes** [comment]
This goes under "High-level system architecture, database organization" in Milestone 2

**Comment by RobinPichu** [comment]
please review the new version of schema, I'll put it in the doc already

**Comment by omegabytes** [comment]
@lspangan would you mind reviewing this? I think it makes sense, but I'm not very experienced with DB stuff.

**Comment by lspangan** [comment]
Yes, i believe it looks good. Everything connects.
