### ISSUE TITLE
High Level UML Diagrams

### ISSUE THREAD

**Issue by omegabytes** [omegabytes/csc648group06#37]
At minimum provide:
a) High-level UML class diagrams for implementation classes of core functionality, i.e. functionality with provided interfaces. Focus on a main high-level classes only (one or at most two levels deep). This must reflect an OO approach to implementing your site.
b) UML Component and deployment diagrams

Use data terms and names consistently with Glossary/Data Dictionary.

**Comment by AnthonyMa2122** [comment]
All written, will redraw for the sake of presentability.
